# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

In [ ]:
# Importing libraries:
import pandas as pd
import numpy as np
import math
import subprocess
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Reading csv file:
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'

df = pd.read_csv(url)
df = df.copy() # safety copy
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [ ]:
# List columns names
df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [ ]:
# Standardize column names
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.replace('st', 'state')

df.head()

,custateomer,state,gender,education,custateomer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [ ]:
df.rename(columns={'custateomer': 'customer'}, inplace=True)

In [ ]:
df.columns

Index(['customer', 'state', 'gender', 'education',
       'custateomer_lifetime_value', 'income', 'monthly_premium_auto',
       'number_of_open_complaints', 'policy_type', 'vehicle_class',
       'total_claim_amount'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer                    1071 non-null   object
 1   state                       1071 non-null   object
 2   gender                      954 non-null    object
 3   education                   1071 non-null   object
 4   custateomer_lifetime_value  1068 non-null   object
 5   income                      1071 non-null   float64
 6   monthly_premium_auto        1071 non-null   float64
 7   number_of_open_complaints   1071 non-null   object
 8   policy_type                 1071 non-null   object
 9   vehicle_class               1071 non-null   object
 10  total_claim_amount          1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [ ]:
df.gender.unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [ ]:
# Standardize the Gender column
gender_mapping = {'F': 'F', 'M': 'M', 'Femal': 'F', 'Male': 'M', 'female': 'F'}
df['gender'] = df['gender'].replace(gender_mapping)

In [ ]:
# Test unique values in the Gender column
print(df['gender'].unique())

[nan 'F' 'M']

In [ ]:
# Test gender change
df.head()

,customer,state,gender,education,custateomer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [ ]:
df.state.unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [ ]:
# Fixing state data

state_mapping = {'AZ': 'arizona', 'Cali': 'california','WA': 'washington'}

# Replace state abbreviations with full names in lowercase in the 'state' column
df['state'] = df['state'].replace(state_mapping)

# Test unique values in 'state'
print(df['state'].unique())

['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' 'california'
 'arizona' 'washington' nan]

In [ ]:
# Replace "Bachelors" with "Bachelor" in the 'education' column
df['education'] = df['education'].replace('Bachelors', 'Bachelor')
df.education.unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [ ]:
# Remove '%' character from 'custateomer_lifetime_value' column
df['custateomer_lifetime_value'] = df['custateomer_lifetime_value'].str.replace('%', '')

In [ ]:
# Fixing vehicle column
vehicle_mapping = {'Sports Car': 'Luxury','Luxury SUV': 'Luxury','Luxury Car': 'Luxury'}

# Replace values in 'vehicle_class' column according to the mapping
df['vehicle_class'] = df['vehicle_class'].replace(vehicle_mapping)

df.head()

,customer,state,gender,education,custateomer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [ ]:
# Changing Customer lifetime to numeric:

df['custateomer_lifetime_value'].fillna(0, inplace=True)

df['custateomer_lifetime_value'] = pd.to_numeric(df['custateomer_lifetime_value'], errors='coerce')

print(df.dtypes)
df.head()

customer                       object
state                          object
gender                         object
education                      object
custateomer_lifetime_value    float64
income                        float64
monthly_premium_auto          float64
number_of_open_complaints      object
policy_type                    object
vehicle_class                  object
total_claim_amount            float64
dtype: object

,customer,state,gender,education,custateomer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,0.00,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [ ]:
# Fixing 'number_of_open_complaints' data

df.number_of_open_complaints.unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

In [ ]:
# Function to map 'number_of_open_complaints' data like '1/5/00' to 5
def extract_middle_value(s):
    if '/' in str(s):
        return s.split('/')[1]
    else:
        return s

# Apply function to 'number_of_open_complaints' column
df['number_of_open_complaints'] = df['number_of_open_complaints'].apply(extract_middle_value)
df['number_of_open_complaints'] = pd.to_numeric(df['number_of_open_complaints'], errors='coerce')

# Test 'number_of_open_complaints'
print(df['number_of_open_complaints'].unique())

df.dtypes.number_of_open_complaints

[ 0.  2.  1.  3.  5.  4. nan]

dtype('float64')

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [ ]:
# Pulling null values info:
null_counts = df.isnull().sum()
print(f"Number of null values (count): {null_counts}")

# Filling with mean the numeric columns and with mode the categorical columns

mean_values = df.mean()
mode_values = df.mode().iloc[0]
fill_values = {
    'custateomer_lifetime_value': mean_values['custateomer_lifetime_value'],
    'income': mean_values['income'],
    'monthly_premium_auto': mean_values['monthly_premium_auto'],
    'number_of_open_complaints': mean_values['number_of_open_complaints'],
    'total_claim_amount': mean_values['total_claim_amount'],
    'customer': mode_values['customer'],
    'state': mode_values['state'],
    'gender': mode_values['gender'],
    'education': mode_values['education'],
    'policy_type': mode_values['policy_type'],
    'vehicle_class': mode_values['vehicle_class']
}

# Fill null values
df.fillna(fill_values, inplace=True)

# Convert numeric variables to integers
numeric_columns = ['custateomer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'total_claim_amount']
df[numeric_columns] = df[numeric_columns].astype(int)

# Verify that null values are handled
print("\nFixing null values:\n", df.isnull().sum())

# Check data types after conversion
print("\nTesting data types:\n", df.dtypes)

Number of null values (count): customer                      0
state                         0
gender                        0
education                     0
custateomer_lifetime_value    0
income                        0
monthly_premium_auto          0
number_of_open_complaints     0
policy_type                   0
vehicle_class                 0
total_claim_amount            0
dtype: int64

Fixing null values:
 customer                      0
state                         0
gender                        0
education                     0
custateomer_lifetime_value    0
income                        0
monthly_premium_auto          0
number_of_open_complaints     0
policy_type                   0
vehicle_class                 0
total_claim_amount            0
dtype: int64

Testing data types:
 customer                      object
state                         object
gender                        object
education                     object
custateomer_lifetime_value     int64
income                         int64
monthly_premium_auto           int64
number_of_open_complaints      int64
policy_type                   object
vehicle_class                 object
total_claim_amount             int64
dtype: object

<ipython-input-21-56e575bed26c>:7: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean_values = df.mean()

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [ ]:
# Check duplicates

duplicates = df.duplicated()
df[duplicates]

,customer,state,gender,education,custateomer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1072,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
1073,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
1074,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
1075,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
1076,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
...,...,...,...,...,...,...,...,...,...,...,...
4003,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
4004,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
4005,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
4006,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404
4007,AA71604,Oregon,F,Bachelor,0,39295,193,0,Personal Auto,Four-Door Car,404

In [ ]:
# Option choosen for duplicates: Dropping all duplicate rows

df_clean = df.drop_duplicates()

# Testing:
print(df_clean.duplicated().any())

df_clean.to_csv('cleaned_data_dropped_duplicates.csv', index=False)

False